# Generated by Django 5.1.1 on 2024-10-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetup', '0002_alter_menu_link_alter_submenu_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubmenu',
            name='link',
            field=models.URLField(blank=True, default='sem_link_salvo.com', null=True),
        ),
    ]
