# Generated by Django 5.1.1 on 2024-10-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetup', '0003_alter_subsubmenu_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.URLField(blank=True, default='sem_link_salvo.com', null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='link',
            field=models.URLField(blank=True, default='sem_link_salvo.com', null=True),
        ),
    ]
