# Generated by Django 5.1.1 on 2024-10-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetup', '0004_alter_menu_link_alter_submenu_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.URLField(blank=True, default='exemplo.com', null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='link',
            field=models.URLField(blank=True, default='exemplo.com', null=True),
        ),
        migrations.AlterField(
            model_name='subsubmenu',
            name='link',
            field=models.URLField(blank=True, default='exemplo.com', null=True),
        ),
    ]
