# Generated by Django 5.1.1 on 2024-10-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetup', '0006_alter_menu_link_alter_submenu_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsubmenu',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
