# Generated by Django 5.1.1 on 2024-10-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetup', '0007_alter_menu_link_alter_submenu_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=255)),
                ('email_port', models.IntegerField()),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(max_length=254)),
                ('email_host_password', models.CharField(max_length=255)),
                ('default_from_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
